[2022-10-01 21:05:20.982] [remoteagent] [info] Extension host agent started.
[2022-10-01 21:05:21.370] [remoteagent] [info] [127.0.0.1][39c28a63][ExtensionHostConnection] New connection established.
[2022-10-01 21:05:21.371] [remoteagent] [info] [127.0.0.1][c79b7954][ManagementConnection] New connection established.
[2022-10-01 21:05:21.387] [remoteagent] [info] [127.0.0.1][39c28a63][ExtensionHostConnection] <18085> Launched Extension Host Process.
[2022-10-01 21:36:04.951] [remoteagent] [warning] No ptyHost heartbeat after 6 seconds
[2022-10-01 21:36:47.646] [remoteagent] [warning] No ptyHost heartbeat after 6 seconds
[2022-10-01 21:37:13.161] [remoteagent] [warning] No ptyHost heartbeat after 6 seconds
[2022-10-01 21:59:13.762] [remoteagent] [error] Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
[2022-10-01 21:59:13.967] [remoteagent] [error] Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
[2022-10-01 21:59:14.199] [remoteagent] [error] Error: connect ECONNREFUSED 127.0.0.1:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
[2022-10-01 22:17:39.748] [remoteagent] [warning] No ptyHost heartbeat after 6 seconds
[2022-10-01 22:18:04.257] [remoteagent] [warning] No ptyHost heartbeat after 6 seconds
[2022-10-01 22:18:06.246] [remoteagent] [info] [127.0.0.1][39c28a63][ExtensionHostConnection] The client has reconnected.
[2022-10-01 22:18:07.257] [remoteagent] [error] ["CodeExpectedError: Could not find pty on pty host","    at c._throwIfNoPty (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:23:36316)","    at c.updateIcon (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:23:32124)","    at Object.call (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:16:8386)","    at u.onPromise (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:15:5851)","    at u.onRawMessage (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:15:5234)","    at /root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:15:4520","    at p.invoke (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:11:145)","    at D.deliver (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)","    at T.fire (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)","    at process.Q (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:9:20703)","    at process.emit (node:events:526:28)","    at emit (node:internal/child_process:938:14)","    at processTicksAndRejections (node:internal/process/task_queues:84:21)"]
[2022-10-01 22:18:07.258] [remoteagent] [error] ["CodeExpectedError: Could not find pty on pty host","    at c._throwIfNoPty (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:23:36316)","    at c.updateTitle (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:23:32064)","    at Object.call (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:16:8386)","    at u.onPromise (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:15:5851)","    at u.onRawMessage (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:15:5234)","    at /root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:15:4520","    at p.invoke (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:11:145)","    at D.deliver (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)","    at T.fire (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)","    at process.Q (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:9:20703)","    at process.emit (node:events:526:28)","    at emit (node:internal/child_process:938:14)","    at processTicksAndRejections (node:internal/process/task_queues:84:21)"]
[2022-10-01 22:18:07.847] [remoteagent] [error] ["CodeExpectedError: Could not find pty on pty host","    at c._throwIfNoPty (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:23:36316)","    at c.updateTitle (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:23:32064)","    at Object.call (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:16:8386)","    at u.onPromise (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:15:5851)","    at u.onRawMessage (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:15:5234)","    at /root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:15:4520","    at p.invoke (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:11:145)","    at D.deliver (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)","    at T.fire (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)","    at process.Q (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:9:20703)","    at process.emit (node:events:526:28)","    at emit (node:internal/child_process:938:14)","    at processTicksAndRejections (node:internal/process/task_queues:84:21)"]
[2022-10-01 22:18:10.212] [remoteagent] [info] [127.0.0.1][c79b7954][ManagementConnection] The client has reconnected.
[2022-10-01 22:18:10.302] [remoteagent] [error] ["CodeExpectedError: Could not find pty on pty host","    at c._throwIfNoPty (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:23:36316)","    at c.updateTitle (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:23:32064)","    at Object.call (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:16:8386)","    at u.onPromise (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:15:5851)","    at u.onRawMessage (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:15:5234)","    at /root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:15:4520","    at p.invoke (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:11:145)","    at D.deliver (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:11:2275)","    at T.fire (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:11:1853)","    at process.Q (/root/.vscode-server/bin/e7f30e38c5a4efafeec8ad52861eb772a9ee4dfb/out/vs/platform/terminal/node/ptyHostMain.js:9:20703)","    at process.emit (node:events:526:28)","    at emit (node:internal/child_process:938:14)","    at processTicksAndRejections (node:internal/process/task_queues:84:21)"]
[2022-10-01 23:17:38.246] [remoteagent] [warning] No ptyHost heartbeat after 6 seconds
[2022-10-01 23:17:54.994] [remoteagent] [info] [127.0.0.1][39c28a63][ExtensionHostConnection] The client has reconnected.
